### ISSUE TITLE
orchestration of xnat service

### ISSUE THREAD

**Issue by vsoch** [NrgXnat/docker-images#1]
hey @nrgxnat-bot team! I am helping to deploy some cloud pipelines at the School of Medicine, and wanted to ask if you have documentation / examples for (likely a docker-compose) that can bring up the database, xnat service, and any dicom bits easily. From poking around your docs and repos I see the container service has modular containers to perform specific functions, and I've also found various (third party) xnat-server repos around Github, but I'm (hopefully) looking for one provided by you guys as a starting point to evaluate. As an example, [here is one](https://github.com/pydicom/sendit/blob/master/docker-compose.yml) that deploys a database, web server, and worker. Thanks in advance!

**Comment by vsoch** [comment]
oh and I'm not sure where to put this, but the links to your docs on the main page are broken! I think they should be pointing here --> https://wiki.xnat.org/display/XNAT17

**Comment by johnflavin** [comment]
Hi, Vanessa. We don't actually have a `docker-compose` file that can make an XNAT. That's something that I have been thinking about doing for a while, because I think it really wouldn't take too much effort and would be very cool, but I just haven't gotten around to it.

What we do have is a Vagrant build, which you can find at https://bitbucket.org/xnatdev/xnat-vagrant. That will download a base VM and provision it with everything XNAT needs to run. (You probably didn't find that repo because everyone else in the lab insists on using BitBucket for reasons I can't fathom.)

What kind of DICOM operations do you need to do? Out of the box XNAT comes with a DICOM receiver, so a scanner can send images directly to XNAT. We have additional code that can search for and pull images from a PACS, but I am not sure if that is up-to-date. If you need it, I can check on it for you.

**Comment by vsoch** [comment]
hey @johnflavin ! I have taken some time and tested out the Vagrant box, along with trying to hack together a docker-compose. The Vagrant box works for me locally, but doesn't work on a cloud VM because it's essentially a VM inside a VM (do you have a working example of this?). The docker-compose examples (there are a few if you google search that I tweaked) I was able to get working, but they are for the older version 1.6x that has a bit more transparent install procedure. Importantly, we would want to separate out the various components (application, web server, database) hence the need for compose. And I think we would want to deploy the updated 1.7, and it would be ideal to have a Dockerized, cloud deployment. Is there anyone working on this? Or anyone that could work with me to figure it out?

**Comment by johnflavin** [comment]
Right now there is no one working on that. But it just so happens that I am going to have some hackathon time at a workshop in a couple weeks, and you just gave me a good idea for a project. I will see what I can put together with a few days of work.

**Comment by vsoch** [comment]
woohoo! I'd love to help, if you want. I can offer to get started on something before the hackathon if you don't have a chance. Where  / how would you go about it?

**Comment by johnflavin** [comment]
I think I would find one of the existing docker compose yaml files that build an XNAT with 1.6.x, and update it for 1.7.x. If you could send me links to what you've found, that would be a good starting point.

While I have experience building and deploying XNAT, I am not super familiar with docker compose. I have used it, but not much beyond the basic tutorials. I don't really know the best practices of how to, for instance, make it so the different parts can scale easily. And I've never used docker with AWS or Google Cloud or any other providers, just on local (or local network) VMs. So it would also be helpful if you could tell me how the various microservices should work together, what your needs are, that sort of thing.

**Comment by vsoch** [comment]
Oh I've already done that, several times in fact, take a look at this folder lol

```
ls stanford-medicine-pipelines/
builder-orthanc              cirr-docker                    orthanc-docker       xnat
django-inotifier               sendit               xnat-docker
docfish                        som-django-template  xnat-docker1
inspecit                       som-orthanc          xnat-vagrant
latex_call_dicom_receiver.txt  somquery
mirc-ctp-node                  som-xnat
```

With compose you are essentially modular-izing the different pieces. The simplest approach would actually first to try to put the entire thing in one docker image (one Dockerfile) and then break out into components when that is working. Is installing 1.6 and then using some programmatic update to 1.7 the best way? My plan was to look / start with your 1.7 Vagrantfile and try to turn it into a Dockerfile approach. Is that the best way?

**Comment by johnflavin** [comment]
I think that deconstructing the Vagrant build scripts could be a good approach. It would be better than starting from a 1.6.x build and trying to update it to a 1.7.x build, because the process of building and deploying XNAT changed so much between those versions.

Standing up an XNAT 1.7 VM / docker container is all about getting the machine set up correctly. Once you have the machine set up, you only have to drop the XNAT war file into tomcat's directory and start tomcat. You don't have to build XNAT anymore, unlike 1.6; the war file is self-contained.

(I guess there is one additional step. If you want the pipeline engine—and, sadly, the pipeline engine is still mandatory if you want any snapshots—you also have to download the source and run its setup script.)

On the other hand, maybe you don't need to do go through the hassle. I searched around and found this, which looks like an OK starting point: https://gitlab.erc.monash.edu.au/mbi-image/containerized-xnat. It would need some work, I think. But they are at least installing a 1.7 XNAT. 

I have also talked about this project with the hosts of the upcoming workshop. They told me they already have a docker-compose yaml that they use for XNAT. Once I get a copy of that it could be another good starting point.

Either way, if you want to get started now or just wait a bit, I'll be working on this next week.

**Comment by johnflavin** [comment]
I've made a repo for this: [nrgxnat/xnat-docker-compose](https://github.com/NrgXnat/xnat-docker-compose). It's based on that repo I linked to in my last comment (I had to essentially steal it. I wanted to make a proper fork, but it's hosted on their university GitLab and not GitHub, so I didn't know how to fork it.)

There are several other people here at the workshop with me who are interested in this project, so we will hopefully be pretty actively developing it at least for the next few days. I think it works right now, but we are making it better. I would be happy to have your input, so feel free to jump right in.

**Comment by vsoch** [comment]
woohoo! I will very happily be a tested and critique when needed. Should I wait for the few days of the workshop and then when you guys are finished up / heading home, jump in?

**Comment by johnflavin** [comment]
Totally up to you. You could absolutely jump in now if you want. Even if you want wait, it would be helpful for you to take a look at what is there now and file an issue if you notice something weird or wrong, or if you think of something you want that isn't there yet.
